name: Backend for ci/cd

on:
  push:
    branches:
      - main

jobs:
  cicd-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout github files
        uses: actions/checkout@v4

      - name: install JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: create application.properties dynamically
        run: |
          echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application.properties
          ls ./src/main/resources/application.properties