name: Backend for ci/cd

on:
  push:
    branches:
      - main

jobs:
  cicd-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout github files
        uses: actions/checkout@v4

      - name: install JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: create application.properties dynamically
        run: |
          echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application.properties
          ls ./src/main/resources/application.properties

      - name: unit test & build
        run: |
          chmod +x ./gradlew
          ./gradlew clean build

      - name: rename output file
        run: |
          mv ./build/libs/*SNAPSHOT.jar ./run.jar
          ls

      - name: upload jar on EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: run.jar
          target: /home/ubuntu/server/demo

      - name: connect with SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script_stop: true
          script: |
            rm -rf /home/ubuntu/server/web
            mkdir /home/ubuntu/server/web
            mv /home/ubuntu/server/demo/run.jar /home/ubuntu/server/web/run.jar
            cd /home/ubuntu/server/web
            sudo fuser -k -n tcp 8080 || true
            nohup java -jar run.jar > ./output.log 2>&1 &
            rm -rf /home/ubuntu/server/demo